//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_APP1_IS2_HistoriasClinicas
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_CONSULTA
    {
        public string ID_MEDICAMENTO { get; set; }
        public Nullable<decimal> ID_CON { get; set; }
        public Nullable<decimal> CANTIDAD_MED { get; set; }
        public Nullable<decimal> PVP_MED { get; set; }
        public Nullable<decimal> CANTDES_MED { get; set; }
    
        public virtual CONSULTA CONSULTA { get; set; }
    }
}
