//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_APP1_IS2_HistoriasClinicas
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADOS()
        {
            this.AREA_TRABAJO = new HashSet<AREA_TRABAJO>();
            this.CONSULTA = new HashSet<CONSULTA>();
        }
    
        public string CEDULA_EMP { get; set; }
        public Nullable<decimal> ID_AREA { get; set; }
        public Nullable<decimal> ID_H { get; set; }
        public string NOMBRES_EMP { get; set; }
        public System.DateTime NACIFECHA_EMP { get; set; }
        public string NACIONALIDAD_EMP { get; set; }
        public string DIRECCIO_EMP { get; set; }
        public string TELEFONO_EMP { get; set; }
        public string EMAIL_EMP { get; set; }
        public string ESTADO_EMP { get; set; }
        public string TIPO_EMP { get; set; }
        public string ACTIVO_EMP { get; set; }
        public string CIUDADNACI_EMP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AREA_TRABAJO> AREA_TRABAJO { get; set; }
        public virtual AREA_TRABAJO AREA_TRABAJO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSULTA> CONSULTA { get; set; }
        public virtual HISTORIAS HISTORIAS { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
