//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_APP1_IS2_HistoriasClinicas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClinicaHistoriaEntities : DbContext
    {
        public ClinicaHistoriaEntities()
            : base("name=ClinicaHistoriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AREA_TRABAJO> AREA_TRABAJO { get; set; }
        public virtual DbSet<CONSULTA> CONSULTA { get; set; }
        public virtual DbSet<DETALLE_CONSULTA> DETALLE_CONSULTA { get; set; }
        public virtual DbSet<EMPLEADOS> EMPLEADOS { get; set; }
        public virtual DbSet<HISTORIAS> HISTORIAS { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
    }
}
