--region Drop Existing Procedures

IF OBJECT_ID('dbo.trx_Insert_DetalleConsultum') IS NOT NULL
	DROP PROCEDURE [dbo].[trx_Insert_DetalleConsultum]

IF OBJECT_ID('dbo.trx_Update_DetalleConsultum') IS NOT NULL
	DROP PROCEDURE [dbo].[trx_Update_DetalleConsultum]

IF OBJECT_ID('dbo.trx_Save_DetalleConsultum') IS NOT NULL
	DROP PROCEDURE [dbo].[trx_Save_DetalleConsultum]

IF OBJECT_ID('dbo.trx_Remove_DetalleConsultum') IS NOT NULL
	DROP PROCEDURE [dbo].[trx_Remove_DetalleConsultum]

IF OBJECT_ID('dbo.trx_Get_DetalleConsultum') IS NOT NULL
	DROP PROCEDURE [dbo].[trx_Get_DetalleConsultum]

IF OBJECT_ID('dbo.trx_Get_DetalleConsultasAll') IS NOT NULL
	DROP PROCEDURE [dbo].[trx_Get_DetalleConsultasAll]

--endregion

GO

--region [dbo].[trx_Insert_DetalleConsultum]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Kankor using CodeSmith 6.0.0.0
-- Template:       StoredProcedures-SqlServer.cst
-- Procedure Name: [dbo].[trx_Insert_DetalleConsultum]
-- Date Generated: martes, 9 de enero de 2018
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[trx_Insert_DetalleConsultum]
	@ID_DET varchar(15),
	@ID_CON numeric(15, 0),
	@CANTIDAD_DET numeric(2, 0),
	@PVP_DET decimal(4, 2),
	@CANTDES_DET numeric(3, 0)
AS
DECLARE @error_number	int,
        @error_proc		nvarchar(126),
        @error_message	nvarchar(2048) 
BEGIN TRY

    BEGIN   TRANSACTION
    
    INSERT  INTO [dbo].[DETALLE_CONSULTA] (
    	    [ID_DET],
			[ID_CON],
			[CANTIDAD_DET],
			[PVP_DET],
			[CANTDES_DET] ) 
    VALUES  (
    	    @ID_DET,
			@ID_CON,
			@CANTIDAD_DET,
			@PVP_DET,
			@CANTDES_DET )
    
    COMMIT  TRANSACTION

END TRY
BEGIN CATCH
	SELECT	@error_number = ERROR_NUMBER(),
			@error_proc = ERROR_PROCEDURE(),
			@error_message = ERROR_MESSAGE() 
	RAISERROR( '%s. Error: ( %d ) en %s', 16, 1, @error_message, @error_number,  @error_proc )
	IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
END CATCH
--endregion

GO

--region [dbo].[trx_Update_DetalleConsultum]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Kankor using CodeSmith 6.0.0.0
-- Template:       StoredProcedures-SqlServer.cst
-- Procedure Name: [dbo].[trx_Update_DetalleConsultum]
-- Date Generated: martes, 9 de enero de 2018
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[trx_Update_DetalleConsultum]
	@ID_DET varchar(15),
	@ID_CON numeric(15, 0),
	@CANTIDAD_DET numeric(2, 0),
	@PVP_DET decimal(4, 2),
	@CANTDES_DET numeric(3, 0)
AS
DECLARE @error_number	int,
        @error_proc		nvarchar(126),
        @error_message	nvarchar(2048) 
BEGIN TRY

    BEGIN   TRANSACTION
    UPDATE  [dbo].[DETALLE_CONSULTA] 
    SET     [ID_CON] = @ID_CON,
			[CANTIDAD_DET] = @CANTIDAD_DET,
			[PVP_DET] = @PVP_DET,
			[CANTDES_DET] = @CANTDES_DET
    WHERE   [ID_DET] = @ID_DET
    COMMIT  TRANSACTION
    
END TRY
BEGIN CATCH
	SELECT	@error_number = ERROR_NUMBER(),
			@error_proc = ERROR_PROCEDURE(),
			@error_message = ERROR_MESSAGE() 
	RAISERROR( '%s. Error: ( %d ) en %s', 16, 1, @error_message, @error_number,  @error_proc )
	IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
END CATCH
--endregion

GO


--region [dbo].[trx_Save_DetalleConsultum]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Kankor using CodeSmith 6.0.0.0
-- Template:       StoredProcedures-SqlServer.cst
-- Procedure Name: [dbo].[trx_Save_DetalleConsultum]
-- Date Generated: martes, 9 de enero de 2018
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[trx_Save_DetalleConsultum]
	@ID_DET varchar(15),
	@ID_CON numeric(15, 0),
	@CANTIDAD_DET numeric(2, 0),
	@PVP_DET decimal(4, 2),
	@CANTDES_DET numeric(3, 0)
AS
DECLARE @error_number	int,
        @error_proc		nvarchar(126),
        @error_message	nvarchar(2048) 
BEGIN TRY

    BEGIN TRANSACTION
    
    IF ISNULL( @ID_DET, '') <> '' BEGIN 
        UPDATE  [dbo].[DETALLE_CONSULTA] 
        SET     [ID_CON] = @ID_CON,
				[CANTIDAD_DET] = @CANTIDAD_DET,
				[PVP_DET] = @PVP_DET,
				[CANTDES_DET] = @CANTDES_DET
    	WHERE   [ID_DET] = @ID_DET
    END
                
    ELSE BEGIN
        INSERT  INTO [dbo].[DETALLE_CONSULTA] (
        	    [ID_DET],
				[ID_CON],
				[CANTIDAD_DET],
				[PVP_DET],
				[CANTDES_DET] ) 
        VALUES  (
        	    @ID_DET,
				@ID_CON,
				@CANTIDAD_DET,
				@PVP_DET,
				@CANTDES_DET )
    END

    COMMIT TRANSACTION
    
    SELECT  ID_DET = @ID_DET

END TRY
BEGIN CATCH
	SELECT	@error_number = ERROR_NUMBER(),
			@error_proc = ERROR_PROCEDURE(),
			@error_message = ERROR_MESSAGE() 
	RAISERROR( '%s. Error: ( %d ) en %s', 16, 1, @error_message, @error_number,  @error_proc )
	IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
END CATCH
--endregion

GO


--region [dbo].[trx_Remove_DetalleConsultum]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Kankor using CodeSmith 6.0.0.0
-- Template:       StoredProcedures-SqlServer.cst
-- Procedure Name: [dbo].[trx_Remove_DetalleConsultum]
-- Date Generated: martes, 9 de enero de 2018
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[trx_Remove_DetalleConsultum]
	@ID_DET varchar(15)
AS
DECLARE @error_number	int,
        @error_proc		nvarchar(126),
        @error_message	nvarchar(2048) 
BEGIN TRY

    BEGIN   TRANSACTION
    DELETE  FROM [dbo].[DETALLE_CONSULTA]
    WHERE   [ID_DET] = @ID_DET
    COMMIT  TRANSACTION
    
END TRY
BEGIN CATCH
	SELECT	@error_number = ERROR_NUMBER(),
			@error_proc = ERROR_PROCEDURE(),
			@error_message = ERROR_MESSAGE() 
	RAISERROR( '%s. Error: ( %d ) en %s', 16, 1, @error_message, @error_number,  @error_proc )
	IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
END CATCH
--endregion

GO

--region [dbo].[trx_Get_DetalleConsultum]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Kankor using CodeSmith 6.0.0.0
-- Template:       StoredProcedures-SqlServer.cst
-- Procedure Name: [dbo].[trx_Get_DetalleConsultum]
-- Date Generated: martes, 9 de enero de 2018
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[trx_Get_DetalleConsultum]
	@ID_DET varchar(15)
AS
DECLARE @error_number	int,
        @error_proc		nvarchar(126),
        @error_message	nvarchar(2048) 
BEGIN TRY

	SET TRANSACTION ISOLATION LEVEL READ COMMITTED

    SELECT  [ID_DET],
			[ID_CON],
			[CANTIDAD_DET],
			[PVP_DET],
			[CANTDES_DET]
    FROM    [dbo].[DETALLE_CONSULTA]
    WHERE   [ID_DET] = @ID_DET

END TRY
BEGIN CATCH
	SELECT	@error_number = ERROR_NUMBER(),
			@error_proc = ERROR_PROCEDURE(),
			@error_message = ERROR_MESSAGE() 
	RAISERROR( '%s. Error: ( %d ) en %s', 16, 1, @error_message, @error_number,  @error_proc )
	IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
END CATCH
--endregion

GO

--region [dbo].[trx_Get_DetalleConsultasAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Kankor using CodeSmith 6.0.0.0
-- Template:       StoredProcedures-SqlServer.cst
-- Procedure Name: [dbo].[trx_Get_DetalleConsultasAll]
-- Date Generated: martes, 9 de enero de 2018
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[trx_Get_DetalleConsultasAll]
AS
DECLARE @error_number	int,
        @error_proc		nvarchar(126),
        @error_message	nvarchar(2048) 
BEGIN TRY

	SET TRANSACTION ISOLATION LEVEL READ COMMITTED

    SELECT  [ID_DET],
			[ID_CON],
			[CANTIDAD_DET],
			[PVP_DET],
			[CANTDES_DET]
    FROM    [dbo].[DETALLE_CONSULTA]

END TRY
BEGIN CATCH
	SELECT	@error_number = ERROR_NUMBER(),
			@error_proc = ERROR_PROCEDURE(),
			@error_message = ERROR_MESSAGE() 
	RAISERROR( '%s. Error: ( %d ) en %s', 16, 1, @error_message, @error_number,  @error_proc )
	IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
END CATCH
--endregion

GO

