--region Drop Existing Procedures

IF OBJECT_ID('dbo.trx_Insert_Historia') IS NOT NULL
	DROP PROCEDURE [dbo].[trx_Insert_Historia]

IF OBJECT_ID('dbo.trx_Update_Historia') IS NOT NULL
	DROP PROCEDURE [dbo].[trx_Update_Historia]

IF OBJECT_ID('dbo.trx_Save_Historia') IS NOT NULL
	DROP PROCEDURE [dbo].[trx_Save_Historia]

IF OBJECT_ID('dbo.trx_Remove_Historia') IS NOT NULL
	DROP PROCEDURE [dbo].[trx_Remove_Historia]

IF OBJECT_ID('dbo.trx_Get_Historia') IS NOT NULL
	DROP PROCEDURE [dbo].[trx_Get_Historia]

IF OBJECT_ID('dbo.trx_Get_HistoriasAll') IS NOT NULL
	DROP PROCEDURE [dbo].[trx_Get_HistoriasAll]

--endregion

GO

--region [dbo].[trx_Insert_Historia]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Kankor using CodeSmith 6.0.0.0
-- Template:       StoredProcedures-SqlServer.cst
-- Procedure Name: [dbo].[trx_Insert_Historia]
-- Date Generated: martes, 9 de enero de 2018
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[trx_Insert_Historia]
	@CEDULA_EMP varchar(13),
	@PADRE_H varchar(200),
	@MADRE_H varchar(200),
	@FALLECIDO_P_H char(2),
	@FALLECIDO_M_H char(2),
	@CAUSAS_P_H text,
	@CAUSAS_M_H text,
	@NUM_H_H numeric(2, 0),
	@VIVO_H_H numeric(2, 0),
	@MUERTE_H_H numeric(2, 0),
	@CAUSAS_H_H text,
	@SON_H numeric(2, 0),
	@VIVO_SON_H numeric(2, 0),
	@MUERTOS_SON_H numeric(2, 0),
	@CAUSAS_SON_H text,
	@ALCOHOL_H char(2),
	@TABACO_H char(2),
	@DROGAS_H char(2),
	@FRECUENCIA_TAB_H text,
	@FRECUENCIA_ALC_H text,
	@FRECUENCIA_DRO_H text,
	@ALIMENTACION_H text,
	@DIPSIA_H char(2),
	@PARADIPSIA char(2),
	@FRECUENCIA_PARADIPSIA text,
	@INSOMNIO_H char(2),
	@FRECUENCIA_INSOM_H text,
	@OTRO_H text
AS
DECLARE @error_number	int,
        @error_proc		nvarchar(126),
        @error_message	nvarchar(2048) 
BEGIN TRY

    BEGIN   TRANSACTION
    
    INSERT  INTO [dbo].[HISTORIAS] (
    	    [CEDULA_EMP],
			[PADRE_H],
			[MADRE_H],
			[FALLECIDO_P_H],
			[FALLECIDO_M_H],
			[CAUSAS_P_H],
			[CAUSAS_M_H],
			[NUM_H_H],
			[VIVO_H_H],
			[MUERTE_H_H],
			[CAUSAS_H_H],
			[SON_H],
			[VIVO_SON_H],
			[MUERTOS_SON_H],
			[CAUSAS_SON_H],
			[ALCOHOL_H],
			[TABACO_H],
			[DROGAS_H],
			[FRECUENCIA_TAB_H],
			[FRECUENCIA_ALC_H],
			[FRECUENCIA_DRO_H],
			[ALIMENTACION_H],
			[DIPSIA_H],
			[PARADIPSIA],
			[FRECUENCIA_PARADIPSIA],
			[INSOMNIO_H],
			[FRECUENCIA_INSOM_H],
			[OTRO_H] ) 
    VALUES  (
    	    @CEDULA_EMP,
			@PADRE_H,
			@MADRE_H,
			@FALLECIDO_P_H,
			@FALLECIDO_M_H,
			@CAUSAS_P_H,
			@CAUSAS_M_H,
			@NUM_H_H,
			@VIVO_H_H,
			@MUERTE_H_H,
			@CAUSAS_H_H,
			@SON_H,
			@VIVO_SON_H,
			@MUERTOS_SON_H,
			@CAUSAS_SON_H,
			@ALCOHOL_H,
			@TABACO_H,
			@DROGAS_H,
			@FRECUENCIA_TAB_H,
			@FRECUENCIA_ALC_H,
			@FRECUENCIA_DRO_H,
			@ALIMENTACION_H,
			@DIPSIA_H,
			@PARADIPSIA,
			@FRECUENCIA_PARADIPSIA,
			@INSOMNIO_H,
			@FRECUENCIA_INSOM_H,
			@OTRO_H )
    
    COMMIT  TRANSACTION

END TRY
BEGIN CATCH
	SELECT	@error_number = ERROR_NUMBER(),
			@error_proc = ERROR_PROCEDURE(),
			@error_message = ERROR_MESSAGE() 
	RAISERROR( '%s. Error: ( %d ) en %s', 16, 1, @error_message, @error_number,  @error_proc )
	IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
END CATCH
--endregion

GO

--region [dbo].[trx_Update_Historia]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Kankor using CodeSmith 6.0.0.0
-- Template:       StoredProcedures-SqlServer.cst
-- Procedure Name: [dbo].[trx_Update_Historia]
-- Date Generated: martes, 9 de enero de 2018
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[trx_Update_Historia]
	@CEDULA_EMP varchar(13),
	@PADRE_H varchar(200),
	@MADRE_H varchar(200),
	@FALLECIDO_P_H char(2),
	@FALLECIDO_M_H char(2),
	@CAUSAS_P_H text,
	@CAUSAS_M_H text,
	@NUM_H_H numeric(2, 0),
	@VIVO_H_H numeric(2, 0),
	@MUERTE_H_H numeric(2, 0),
	@CAUSAS_H_H text,
	@SON_H numeric(2, 0),
	@VIVO_SON_H numeric(2, 0),
	@MUERTOS_SON_H numeric(2, 0),
	@CAUSAS_SON_H text,
	@ALCOHOL_H char(2),
	@TABACO_H char(2),
	@DROGAS_H char(2),
	@FRECUENCIA_TAB_H text,
	@FRECUENCIA_ALC_H text,
	@FRECUENCIA_DRO_H text,
	@ALIMENTACION_H text,
	@DIPSIA_H char(2),
	@PARADIPSIA char(2),
	@FRECUENCIA_PARADIPSIA text,
	@INSOMNIO_H char(2),
	@FRECUENCIA_INSOM_H text,
	@OTRO_H text
AS
DECLARE @error_number	int,
        @error_proc		nvarchar(126),
        @error_message	nvarchar(2048) 
BEGIN TRY

    BEGIN   TRANSACTION
    UPDATE  [dbo].[HISTORIAS] 
    SET     [PADRE_H] = @PADRE_H,
			[MADRE_H] = @MADRE_H,
			[FALLECIDO_P_H] = @FALLECIDO_P_H,
			[FALLECIDO_M_H] = @FALLECIDO_M_H,
			[CAUSAS_P_H] = @CAUSAS_P_H,
			[CAUSAS_M_H] = @CAUSAS_M_H,
			[NUM_H_H] = @NUM_H_H,
			[VIVO_H_H] = @VIVO_H_H,
			[MUERTE_H_H] = @MUERTE_H_H,
			[CAUSAS_H_H] = @CAUSAS_H_H,
			[SON_H] = @SON_H,
			[VIVO_SON_H] = @VIVO_SON_H,
			[MUERTOS_SON_H] = @MUERTOS_SON_H,
			[CAUSAS_SON_H] = @CAUSAS_SON_H,
			[ALCOHOL_H] = @ALCOHOL_H,
			[TABACO_H] = @TABACO_H,
			[DROGAS_H] = @DROGAS_H,
			[FRECUENCIA_TAB_H] = @FRECUENCIA_TAB_H,
			[FRECUENCIA_ALC_H] = @FRECUENCIA_ALC_H,
			[FRECUENCIA_DRO_H] = @FRECUENCIA_DRO_H,
			[ALIMENTACION_H] = @ALIMENTACION_H,
			[DIPSIA_H] = @DIPSIA_H,
			[PARADIPSIA] = @PARADIPSIA,
			[FRECUENCIA_PARADIPSIA] = @FRECUENCIA_PARADIPSIA,
			[INSOMNIO_H] = @INSOMNIO_H,
			[FRECUENCIA_INSOM_H] = @FRECUENCIA_INSOM_H,
			[OTRO_H] = @OTRO_H
    WHERE   [CEDULA_EMP] = @CEDULA_EMP
    COMMIT  TRANSACTION
    
END TRY
BEGIN CATCH
	SELECT	@error_number = ERROR_NUMBER(),
			@error_proc = ERROR_PROCEDURE(),
			@error_message = ERROR_MESSAGE() 
	RAISERROR( '%s. Error: ( %d ) en %s', 16, 1, @error_message, @error_number,  @error_proc )
	IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
END CATCH
--endregion

GO


--region [dbo].[trx_Save_Historia]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Kankor using CodeSmith 6.0.0.0
-- Template:       StoredProcedures-SqlServer.cst
-- Procedure Name: [dbo].[trx_Save_Historia]
-- Date Generated: martes, 9 de enero de 2018
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[trx_Save_Historia]
	@CEDULA_EMP varchar(13),
	@PADRE_H varchar(200),
	@MADRE_H varchar(200),
	@FALLECIDO_P_H char(2),
	@FALLECIDO_M_H char(2),
	@CAUSAS_P_H text,
	@CAUSAS_M_H text,
	@NUM_H_H numeric(2, 0),
	@VIVO_H_H numeric(2, 0),
	@MUERTE_H_H numeric(2, 0),
	@CAUSAS_H_H text,
	@SON_H numeric(2, 0),
	@VIVO_SON_H numeric(2, 0),
	@MUERTOS_SON_H numeric(2, 0),
	@CAUSAS_SON_H text,
	@ALCOHOL_H char(2),
	@TABACO_H char(2),
	@DROGAS_H char(2),
	@FRECUENCIA_TAB_H text,
	@FRECUENCIA_ALC_H text,
	@FRECUENCIA_DRO_H text,
	@ALIMENTACION_H text,
	@DIPSIA_H char(2),
	@PARADIPSIA char(2),
	@FRECUENCIA_PARADIPSIA text,
	@INSOMNIO_H char(2),
	@FRECUENCIA_INSOM_H text,
	@OTRO_H text
AS
DECLARE @error_number	int,
        @error_proc		nvarchar(126),
        @error_message	nvarchar(2048) 
BEGIN TRY

    BEGIN TRANSACTION
    
    IF ISNULL( @CEDULA_EMP, '') <> '' BEGIN 
        UPDATE  [dbo].[HISTORIAS] 
        SET     [PADRE_H] = @PADRE_H,
				[MADRE_H] = @MADRE_H,
				[FALLECIDO_P_H] = @FALLECIDO_P_H,
				[FALLECIDO_M_H] = @FALLECIDO_M_H,
				[CAUSAS_P_H] = @CAUSAS_P_H,
				[CAUSAS_M_H] = @CAUSAS_M_H,
				[NUM_H_H] = @NUM_H_H,
				[VIVO_H_H] = @VIVO_H_H,
				[MUERTE_H_H] = @MUERTE_H_H,
				[CAUSAS_H_H] = @CAUSAS_H_H,
				[SON_H] = @SON_H,
				[VIVO_SON_H] = @VIVO_SON_H,
				[MUERTOS_SON_H] = @MUERTOS_SON_H,
				[CAUSAS_SON_H] = @CAUSAS_SON_H,
				[ALCOHOL_H] = @ALCOHOL_H,
				[TABACO_H] = @TABACO_H,
				[DROGAS_H] = @DROGAS_H,
				[FRECUENCIA_TAB_H] = @FRECUENCIA_TAB_H,
				[FRECUENCIA_ALC_H] = @FRECUENCIA_ALC_H,
				[FRECUENCIA_DRO_H] = @FRECUENCIA_DRO_H,
				[ALIMENTACION_H] = @ALIMENTACION_H,
				[DIPSIA_H] = @DIPSIA_H,
				[PARADIPSIA] = @PARADIPSIA,
				[FRECUENCIA_PARADIPSIA] = @FRECUENCIA_PARADIPSIA,
				[INSOMNIO_H] = @INSOMNIO_H,
				[FRECUENCIA_INSOM_H] = @FRECUENCIA_INSOM_H,
				[OTRO_H] = @OTRO_H
    	WHERE   [CEDULA_EMP] = @CEDULA_EMP
    END
                
    ELSE BEGIN
        INSERT  INTO [dbo].[HISTORIAS] (
        	    [CEDULA_EMP],
				[PADRE_H],
				[MADRE_H],
				[FALLECIDO_P_H],
				[FALLECIDO_M_H],
				[CAUSAS_P_H],
				[CAUSAS_M_H],
				[NUM_H_H],
				[VIVO_H_H],
				[MUERTE_H_H],
				[CAUSAS_H_H],
				[SON_H],
				[VIVO_SON_H],
				[MUERTOS_SON_H],
				[CAUSAS_SON_H],
				[ALCOHOL_H],
				[TABACO_H],
				[DROGAS_H],
				[FRECUENCIA_TAB_H],
				[FRECUENCIA_ALC_H],
				[FRECUENCIA_DRO_H],
				[ALIMENTACION_H],
				[DIPSIA_H],
				[PARADIPSIA],
				[FRECUENCIA_PARADIPSIA],
				[INSOMNIO_H],
				[FRECUENCIA_INSOM_H],
				[OTRO_H] ) 
        VALUES  (
        	    @CEDULA_EMP,
				@PADRE_H,
				@MADRE_H,
				@FALLECIDO_P_H,
				@FALLECIDO_M_H,
				@CAUSAS_P_H,
				@CAUSAS_M_H,
				@NUM_H_H,
				@VIVO_H_H,
				@MUERTE_H_H,
				@CAUSAS_H_H,
				@SON_H,
				@VIVO_SON_H,
				@MUERTOS_SON_H,
				@CAUSAS_SON_H,
				@ALCOHOL_H,
				@TABACO_H,
				@DROGAS_H,
				@FRECUENCIA_TAB_H,
				@FRECUENCIA_ALC_H,
				@FRECUENCIA_DRO_H,
				@ALIMENTACION_H,
				@DIPSIA_H,
				@PARADIPSIA,
				@FRECUENCIA_PARADIPSIA,
				@INSOMNIO_H,
				@FRECUENCIA_INSOM_H,
				@OTRO_H )
    END

    COMMIT TRANSACTION
    
    SELECT  CEDULA_EMP = @CEDULA_EMP

END TRY
BEGIN CATCH
	SELECT	@error_number = ERROR_NUMBER(),
			@error_proc = ERROR_PROCEDURE(),
			@error_message = ERROR_MESSAGE() 
	RAISERROR( '%s. Error: ( %d ) en %s', 16, 1, @error_message, @error_number,  @error_proc )
	IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
END CATCH
--endregion

GO


--region [dbo].[trx_Remove_Historia]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Kankor using CodeSmith 6.0.0.0
-- Template:       StoredProcedures-SqlServer.cst
-- Procedure Name: [dbo].[trx_Remove_Historia]
-- Date Generated: martes, 9 de enero de 2018
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[trx_Remove_Historia]
	@CEDULA_EMP varchar(13)
AS
DECLARE @error_number	int,
        @error_proc		nvarchar(126),
        @error_message	nvarchar(2048) 
BEGIN TRY

    BEGIN   TRANSACTION
    DELETE  FROM [dbo].[HISTORIAS]
    WHERE   [CEDULA_EMP] = @CEDULA_EMP
    COMMIT  TRANSACTION
    
END TRY
BEGIN CATCH
	SELECT	@error_number = ERROR_NUMBER(),
			@error_proc = ERROR_PROCEDURE(),
			@error_message = ERROR_MESSAGE() 
	RAISERROR( '%s. Error: ( %d ) en %s', 16, 1, @error_message, @error_number,  @error_proc )
	IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
END CATCH
--endregion

GO

--region [dbo].[trx_Get_Historia]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Kankor using CodeSmith 6.0.0.0
-- Template:       StoredProcedures-SqlServer.cst
-- Procedure Name: [dbo].[trx_Get_Historia]
-- Date Generated: martes, 9 de enero de 2018
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[trx_Get_Historia]
	@CEDULA_EMP varchar(13)
AS
DECLARE @error_number	int,
        @error_proc		nvarchar(126),
        @error_message	nvarchar(2048) 
BEGIN TRY

	SET TRANSACTION ISOLATION LEVEL READ COMMITTED

    SELECT  [CEDULA_EMP],
			[PADRE_H],
			[MADRE_H],
			[FALLECIDO_P_H],
			[FALLECIDO_M_H],
			[CAUSAS_P_H],
			[CAUSAS_M_H],
			[NUM_H_H],
			[VIVO_H_H],
			[MUERTE_H_H],
			[CAUSAS_H_H],
			[SON_H],
			[VIVO_SON_H],
			[MUERTOS_SON_H],
			[CAUSAS_SON_H],
			[ALCOHOL_H],
			[TABACO_H],
			[DROGAS_H],
			[FRECUENCIA_TAB_H],
			[FRECUENCIA_ALC_H],
			[FRECUENCIA_DRO_H],
			[ALIMENTACION_H],
			[DIPSIA_H],
			[PARADIPSIA],
			[FRECUENCIA_PARADIPSIA],
			[INSOMNIO_H],
			[FRECUENCIA_INSOM_H],
			[OTRO_H]
    FROM    [dbo].[HISTORIAS]
    WHERE   [CEDULA_EMP] = @CEDULA_EMP

END TRY
BEGIN CATCH
	SELECT	@error_number = ERROR_NUMBER(),
			@error_proc = ERROR_PROCEDURE(),
			@error_message = ERROR_MESSAGE() 
	RAISERROR( '%s. Error: ( %d ) en %s', 16, 1, @error_message, @error_number,  @error_proc )
	IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
END CATCH
--endregion

GO

--region [dbo].[trx_Get_HistoriasAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Kankor using CodeSmith 6.0.0.0
-- Template:       StoredProcedures-SqlServer.cst
-- Procedure Name: [dbo].[trx_Get_HistoriasAll]
-- Date Generated: martes, 9 de enero de 2018
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[trx_Get_HistoriasAll]
AS
DECLARE @error_number	int,
        @error_proc		nvarchar(126),
        @error_message	nvarchar(2048) 
BEGIN TRY

	SET TRANSACTION ISOLATION LEVEL READ COMMITTED

    SELECT  [CEDULA_EMP],
			[PADRE_H],
			[MADRE_H],
			[FALLECIDO_P_H],
			[FALLECIDO_M_H],
			[CAUSAS_P_H],
			[CAUSAS_M_H],
			[NUM_H_H],
			[VIVO_H_H],
			[MUERTE_H_H],
			[CAUSAS_H_H],
			[SON_H],
			[VIVO_SON_H],
			[MUERTOS_SON_H],
			[CAUSAS_SON_H],
			[ALCOHOL_H],
			[TABACO_H],
			[DROGAS_H],
			[FRECUENCIA_TAB_H],
			[FRECUENCIA_ALC_H],
			[FRECUENCIA_DRO_H],
			[ALIMENTACION_H],
			[DIPSIA_H],
			[PARADIPSIA],
			[FRECUENCIA_PARADIPSIA],
			[INSOMNIO_H],
			[FRECUENCIA_INSOM_H],
			[OTRO_H]
    FROM    [dbo].[HISTORIAS]

END TRY
BEGIN CATCH
	SELECT	@error_number = ERROR_NUMBER(),
			@error_proc = ERROR_PROCEDURE(),
			@error_message = ERROR_MESSAGE() 
	RAISERROR( '%s. Error: ( %d ) en %s', 16, 1, @error_message, @error_number,  @error_proc )
	IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
END CATCH
--endregion

GO

