//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_HistoriasClinicas
{
    using System;
    using System.Collections.Generic;
    
    public partial class listado_facturacion
    {
        public string CEDULA_EMP { get; set; }
        public string NOMBRES_EMP { get; set; }
        public System.DateTime NACIFECHA_EMP { get; set; }
        public string NACIONALIDAD_EMP { get; set; }
        public string DIRECCIO_EMP { get; set; }
        public string TELEFONO_EMP { get; set; }
        public string EMAIL_EMP { get; set; }
        public string ESTADO_EMP { get; set; }
        public string ACTIVO_EMP { get; set; }
        public string CIUDADNACI_EMP { get; set; }
        public string CARGO_US { get; set; }
        public string NOMBRE_AREA { get; set; }
        public string DESCRIPCION_AREA { get; set; }
    }
}
