//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_HistoriasClinicas
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVINCIA
    {
        public int cod_provincia { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> cod_pais { get; set; }
    
        public virtual PAI PAI { get; set; }
    }
}
